swagger: "2.0"
info:
  description: "The hierarchy API provides hierarchical models for codelists."
  version: "1.0.0"
  title: "Hierarchy API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
- "http"
parameters:
  instance_id:
    name: instance_id
    type: string
    required: true
    description: "The ID of the instance"
    in: path
  dimension_name:
    name: dimension_name
    type: string
    required: true
    description: "The name of the dimension"
    in: path
  code_id:
    name: code_id
    type: string
    required: true
    description: "The ID of the code"
    in: path
paths:
  /hierarchies/{instance_id}/{dimension_name}:
    parameters:
      - $ref: '#/parameters/instance_id'
      - $ref: '#/parameters/dimension_name'
    get:
      summary: "Get the hierarchy for the given dimension name"
      description: "Get the hierarchy for the given dimension name"
      produces:
      - "application/json"
      responses:
        200:
          description: "The hierarchy was found and returned"
          schema:
            $ref: '#/definitions/HierarchyResponse'
        400:
          $ref: '#/responses/InstanceNotFound'
        404:
          $ref: '#/responses/DimensionNotFound'
        500:
          $ref: '#/responses/InternalError'
  /hierarchies/{instance_id}/{dimension_name}}/{code_id}:
    parameters:
      - $ref: '#/parameters/instance_id'
      - $ref: '#/parameters/dimension_name'
      - $ref: '#/parameters/code_id'
    get:
      summary: "Get a description of a filter job"
      description: "Get document describing the filter job"
      produces:
      - "application/json"
      responses:
        200:
          description: "The filter job was found and document is returned"
          schema:
            $ref: '#/definitions/CodeResponse'
        400:
          $ref: '#/responses/InstanceOrDimensionNotFound'
        404:
          $ref: '#/responses/CodeNotFound'
        500:
          $ref: '#/responses/InternalError'
responses:
  InstanceNotFound:
    description: "Instance not found"
  DimensionNotFound:
    description: "Dimension not found"
  InstanceOrDimensionNotFound:
    description: "Instance or dimension name not found"
  CodeNotFound:
    description: "Code not found"
  InternalError:
    description: "Failed to process the request due to an internal error"
definitions:
  HierarchyResponse:
    description: ""
    type: object
    properties:
      links:
        $ref: '#/definitions/HierarchyLinks'
      children:
        type: array
        description: "The top level nodes of this hierarchy"
        items:
          type: object
          items:
              $ref: '#/definitions/HierarchyChild'
  HierarchyLinks:
    description: "A list of links related to this hierarchy"
    readOnly: true
    type: object
    properties:
      self:
        $ref: '#/definitions/SelfLink'
      dimension:
        $ref: '#/definitions/DimensionLink'
  HierarchyChild:
    type: object
    readOnly: true
    properties:
      links:
        $ref: '#/definitions/HierarchyChildLinks'
      label:
        type: string
        description: "The label for this child node"
      code:
        type: string
        description: "The code for this child node"
      no_of_children:
        type: integer
        description: "The number of child nodes that this node has"
  HierarchyChildLinks:
    description: "A list of links related to this node"
    readOnly: true
    type: object
    properties:
      self:
        $ref: '#/definitions/SelfLink'
  CodeResponse:
    description: ""
    type: object
    properties:
      links:
        $ref: '#/definitions/CodeLinks'
      label:
        type: string
        description: "The label for this node"
      code:
        type: string
        description: "The code for this node"
      has_data:
        type: boolean
        description: "True if the instance has an observation for this code"
      children:
        type: array
        description: "The child nodes of this node in the hierarchy"
        items:
          type: object
          items:
            $ref: '#/definitions/CodeChild'
  CodeLinks:
    description: "A list of links related to this code"
    readOnly: true
    type: object
    properties:
      self:
        $ref: '#/definitions/SelfLink'
      code:
        $ref: '#/definitions/CodeLink'
      dimension_option:
        $ref: '#/definitions/DimensionOptionLink'
      parent:
        $ref: '#/definitions/ParentLink'
  CodeChild:
    type: object
    readOnly: true
    properties:
      links:
        $ref: '#/definitions/CodeChildLinks'
      label:
        type: string
        description: "The label for this child node"
      code:
        type: string
        description: "The code for this child node"
      no_of_children:
        type: integer
        description: "The number of child nodes that this node has"
  CodeChildLinks:
    description: "A list of links related to this node"
    readOnly: true
    type: object
    properties:
      self:
        $ref: '#/definitions/SelfLink'
      parent:
        $ref: '#/definitions/ParentLink'
      code:
        $ref: '#/definitions/CodeLink'
  SelfLink:
    description: "A link to this resource"
    readOnly: true
    type: object
    properties:
      href:
        type: string
  DimensionLink:
    type: object
    readOnly: true
    properties:
      href:
        description: "A link to the dimension"
        example: "http://localhost:8080/dataset/CPI/edition/2017/v/3/dimensions/CPIAggregate"
        type: string
  DimensionOptionLink:
    type: object
    readOnly: true
    properties:
      href:
        description: "A link to the dimension option"
        example: "http://localhost:8080/dataset/CPI/edition/2017/v/3/dimensions/CPIAggregate/option/09"
        type: string
  ParentLink:
    type: object
    readOnly: true
    properties:
      href:
        description: "A link to the parent node of this node"
        example: "http://localhost:8080/hierarchies/i1234/CPIAggregate/09"
        type: string
  CodeLink:
    type: object
    readOnly: true
    properties:
      href:
        description: "A link to the code related to this node"
        example: "http://localhost:8080//code-lists/c345/codes/09.1"
        type: string