swagger: '2.0'
info:
  description: The hierarchy API provides hierarchical views of codelists.
  version: 1.0.0
  title: Hierarchy API
  license:
    name: Open Government Licence v3.0
    url: 'http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'
basePath: /v1
schemes:
  - http
parameters:
  instance_id:
    name: instance_id
    type: string
    required: true
    description: The ID of the instance
    in: path
  dimension_name:
    name: dimension_name
    type: string
    required: true
    description: The name of the dimension
    in: path
  code_id:
    name: code_id
    type: string
    required: true
    description: The ID of the code
    in: path
paths:
  '/hierarchies/{instance_id}/{dimension_name}':
    parameters:
      - $ref: '#/parameters/instance_id'
      - $ref: '#/parameters/dimension_name'
    get:
      summary: Get the root of the hierarchy for the given dimension name
      description: Get the root of the hierarchy for the given dimension name
      produces:
        - application/json
      responses:
        '200':
          description: The hierarchy root was found and returned
          schema:
            $ref: '#/definitions/HierarchyResponse'
        '404':
          $ref: '#/responses/InstanceOrDimensionNotFound'
        '500':
          $ref: '#/responses/InternalError'
  '/hierarchies/{instance_id}/{dimension_name}/{code_id}':
    parameters:
      - $ref: '#/parameters/instance_id'
      - $ref: '#/parameters/dimension_name'
      - $ref: '#/parameters/code_id'
    get:
      summary: Get a specific node in the given hierarchy
      description: Get the document describing a node in a specific hierarchy
      produces:
        - application/json
      responses:
        '200':
          description: The hierarchy node was found and document is returned
          schema:
            $ref: '#/definitions/CodeResponse'
        '404':
          $ref: '#/responses/InstanceOrDimensionOrCodeNotFound'
        '500':
          $ref: '#/responses/InternalError'
responses:
  InstanceOrDimensionNotFound:
    description: Instance or dimension name not found
  InstanceOrDimensionOrCodeNotFound:
    description: 'Instance, dimension or code not found'
  InternalError:
    description: Failed to process the request due to an internal error
definitions:
  Label:
    description: A label for this node
    type: string
  Link:
    description: A link to a given resource
    readOnly: true
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  HierarchyResponse:
    description: The top-level node of a hierarchy
    type: object
    properties:
      label:
        $ref: '#/definitions/Label'
      links:
        $ref: '#/definitions/Links'
      no_of_children:
        type: integer
        description: The number of child nodes that this node has
      has_data:
        type: boolean
        description: True if the instance has an observation for this code
      children:
        type: array
        description: The children of the top-level node of this hierarchy
        items:
          $ref: '#/definitions/NodeRef'
  Links:
    description: A list of links related to this node
    readOnly: true
    type: object
    properties:
      self:
        $ref: '#/definitions/Link'
      code:
        $ref: '#/definitions/Link'
    example:
      self:
        id: abc123
        href: 'http://hierarchy-api/hierarchies/instance_id1/dimension1'
      code:
        id: xyz987
        href: 'http://codelist/code-lists/clist1/codes/xyz987'
  CodeResponse:
    description: ''
    type: object
    properties:
      links:
        $ref: '#/definitions/Links'
      label:
        type: string
        description: The label for this node
      no_of_children:
        type: integer
        description: The number of child nodes that this node has
      has_data:
        type: boolean
        description: True if the instance has an observation for this code
      children:
        type: array
        description: The child nodes of this node in the hierarchy
        items:
          $ref: '#/definitions/NodeRef'
      breadcrumbs:
        type: array
        description: >-
          The ancestors (nodes) of this node in the hierarchy, starting with the
          parent
        items:
          $ref: '#/definitions/NodeRef'
  NodeRef:
    type: object
    readOnly: true
    properties:
      links:
        $ref: '#/definitions/Links'
      label:
        type: string
        description: The label for this child node
      no_of_children:
        type: integer
        description: The number of child nodes that this node has
      has_data:
        type: boolean
        description: True if the instance has an observation for this code
    example:
      label: Transport
      no_of_children: 3
      has_data: 'yes'
      links:
        self:
          id: '123'
          href: 'http://hierarchy-api/hierarchies/{instance_id}/Special_Aggregat/123'
        code:
          id: 987
          href: 'http://codelist-api/code-lists/{code-list-id}/codes/01'