---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.13.8

inputs:
  - name: dp-hierarchy-api

outputs:
  - name: build

run:
  path: dp-hierarchy-api/ci/scripts/build.sh
